on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

    
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setuo python 3.7.17 (x64)
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.17
      - name: install dependencies
        run: |
          make install
      - name: lint with pylint 
        run: |
          make lint
      - name: Test with pytest
        run: |
          make test
      - name: Format Code
        run: |
          make format
